services:
  - type: web
    name: stock-price-prediction
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput && python manage.py shell < create_superuser.py
    startCommand: gunicorn core.wsgi:application --workers=2 --threads=2 --timeout=120 --log-file -
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.9.6
      - key: DEBUG
        value: false
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@example.com
      - key: DJANGO_SUPERUSER_PASSWORD
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: stock-price-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: stock-prediction-system.onrender.com,.onrender.com

databases:
  - name: stock-price-db
    databaseName: stock_price
    user: stock_price_user 